name: crack
channels:
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - tqdm
  - numpy
  - scipy
  - pillow
  - pytorch
  - matplotlib
  - torchvision
  - pip
  - pip:
    - opencv-python
